### PR TITLE
Handle both bash/zsh and deconfuse cr clone

### PR DESCRIPTION
**Pull request by johan**

### CODE REVIEW

**Comment by paulirish** [comment]
Nice! :birthday:

**Comment by addyosmani** [comment]
Great work, @johan!

**Comment by jankeromnes** [comment]
Awesome, thanks @johan! Merged with minor nits.

**Comment by johan** [comment]
By all means — thanks for doing the nitwork yourself! :-) (Surprisingly many projects prefer the round-trippier version of "tell, don't show", which is still very mobile unfriendly on github.)

**Comment by jankeromnes** [comment]
Writing about nits in natural language takes more time than fixing them, the only risk is to offend people - relieved that you weren't! Also, I'm working on fixing the mobile-unfriendliness of patches and code reviews in my spare time, but that's probably going to take a while.

**Pull request merged**
